name: Deploy Mainnet
on:
  workflow_dispatch:
    inputs: 
      tag:
        description: 'Tag'
        required: true 
        type: string 
env:
  RUST_TOOLCHAIN: stable
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: mainnet
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CROSSREPOTRIGGER }}
          script: |

            let params = {
              owner: "metaplex-foundation",
              repo: "read-api-deployment"
            };

            let release = await github.rest.repos.getReleaseByTag({owner: "metaplex-foundation", repo: "digital-asset-rpc-infrastructure", tag: "${{ inputs.tag }}"});

            await github.rest.repos.createDispatchEvent(Object.assign({
              event_type: "deploy_trigger",
              client_payload: {
                DEPLOY_VERSION: "${{ inputs.tag }}",
                DEPLOY_ENV: "mainnet",
                DEPLOY_K8S_NAMESPACE: "mainnet-read-api",
                DEPLOY_K8S_CLUSTER: "metaplex-prod-001",
              }
            }, params));